# Generated by Django 5.2.3 on 2025-11-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_orderitems_order_alter_orderitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
            preserve_default=False,
        ),
    ]
